"""Updated 'goals' table to allow nullable for circle_id

Revision ID: 19f03ac4deac
Revises: 2623c2c925d1
Create Date: 2025-05-26 23:50:54.809587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19f03ac4deac'
down_revision = '2623c2c925d1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('circle_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('goals', schema=None) as batch_op:
        batch_op.alter_column('circle_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
