"""empty message

Revision ID: 1aa609b1cde4
Revises: 707f761a0918
Create Date: 2025-04-27 22:03:16.625519

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1aa609b1cde4'
down_revision = '707f761a0918'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_staff',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.Boolean(),
               postgresql_using="CASE WHEN is_staff='true' THEN true ELSE false END",
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('is_staff',
               existing_type=sa.Boolean(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
