"""changed column name in CircleMessageModel from 'content' to 'message'

Revision ID: 3a0421d4554c
Revises: 1c9505d3429f
Create Date: 2025-05-24 22:11:29.942273

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a0421d4554c'
down_revision = '1c9505d3429f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('message', sa.String(length=255), nullable=False))
        batch_op.drop_column('content')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('circle_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
        batch_op.drop_column('message')

    # ### end Alembic commands ###
