"""Update User model's account created date generation logic

Revision ID: 9a7af61206e4
Revises: 1aa609b1cde4
Create Date: 2025-05-10 19:07:00.547433

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9a7af61206e4'
down_revision = '1aa609b1cde4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('account_created_date',
               existing_type=sa.VARCHAR(length=80),
               type_=sa.DateTime(),
               postgresql_using="account_created_date::timestamp without time zone",
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('account_created_date',
               existing_type=sa.DateTime(),
               type_=sa.VARCHAR(length=80),
               existing_nullable=False)

    # ### end Alembic commands ###
